#include "game/SaveGame.h"
#include "character/CharClass.h"
#include "character/Equipment.h"
#include "character/Knighthood.h"
#include "character/Race.h"
#include "character/WizardOrder.h"

#include <fstream>
#include <sstream>
#include <stdexcept>
#include <utility>

namespace game {

namespace {

// Same trim/splitKeyword/fail idioms as WorldLoader.cpp and ZoneLoader.cpp --
// each loader in this project owns its own tiny copy rather than sharing a
// utility file (see docs/ARCHITECTURE.md).
std::string trim(const std::string& s) {
    size_t begin = s.find_first_not_of(" \t\r\n");
    if (begin == std::string::npos) return "";
    size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(begin, end - begin + 1);
}

std::pair<std::string, std::string> splitKeyword(const std::string& line) {
    size_t sp = line.find_first_of(" \t");
    if (sp == std::string::npos) return {line, ""};
    return {line.substr(0, sp), trim(line.substr(sp + 1))};
}

[[noreturn]] void fail(const std::string& path, int lineNumber, const std::string& message) {
    throw std::runtime_error(path + ":" + std::to_string(lineNumber) + ": " + message);
}

// RACE/CLASS/ALIGNMENT are stored as raw enum ints (not names) -- simpler
// than adding name<->enum reverse lookups nothing else needs, at the cost
// of a documented fragility: reordering RaceId/ClassId/Alignment silently
// invalidates old saves. Acceptable for a single-slot personal save file --
// see docs/GOTCHAS.md.
template <typename EnumT>
EnumT parseEnumInt(const std::string& path, int lineNumber, const std::string& token,
                    const char* fieldName, int maxExclusive) {
    std::istringstream iss(token);
    int value = -1;
    if (!(iss >> value) || value < 0 || value >= maxExclusive) {
        fail(path, lineNumber, std::string(fieldName) + " is missing or out of range: '" + token + "'");
    }
    return static_cast<EnumT>(value);
}

} // namespace

bool SaveGame::exists(const std::string& path) {
    std::ifstream file(path);
    return file.good();
}

void SaveGame::save(const GameState& state, const std::string& path) {
    const character::Character& c = state.character;
    std::ofstream file(path, std::ios::trunc);
    if (!file) {
        throw std::runtime_error("Could not open save file for writing: " + path);
    }

    file << "# Ansalon RPG savegame -- autogenerated by game::SaveGame::save.\n";
    file << "# Plain text on purpose (see docs/GOTCHAS.md), but not meant for\n";
    file << "# hand-editing -- RACE/CLASS/ALIGNMENT are raw enum ints, and\n";
    file << "# ZONESTACK's entry lines must immediately follow it, in order.\n";
    file << "NAME " << c.name << "\n";
    file << "RACE " << static_cast<int>(c.race) << "\n";
    file << "SUBRACE " << static_cast<int>(c.subrace) << "\n";
    file << "CLASS " << static_cast<int>(c.charClass) << "\n";
    file << "ALIGNMENT " << static_cast<int>(c.alignment) << "\n";
    file << "KNIGHTORDER " << static_cast<int>(c.knightOrder) << "\n";
    file << "ROBE " << static_cast<int>(c.robeColor) << "\n";
    file << "SCORES " << c.scores.strength << " " << c.scores.dexterity << " "
         << c.scores.constitution << " " << c.scores.intelligence << " " << c.scores.wisdom
         << " " << c.scores.charisma << "\n";
    file << "STRPCT " << c.exceptionalStrengthPercentile << "\n";
    file << "LEVEL " << c.level << "\n";
    file << "EXP " << c.experience << "\n";
    file << "HP " << c.currentHp << " " << c.maxHp << "\n";
    file << "AC " << c.armorClass << "\n";
    file << "THAC0 " << c.thac0 << "\n";
    file << "SAVES";
    for (int i = 0; i < static_cast<int>(character::SaveCategory::Count); ++i) {
        file << " " << c.saves.at(static_cast<character::SaveCategory>(i));
    }
    file << "\n";
    file << "STEEL " << c.steelPieces << "\n";
    file << "ARMOR " << static_cast<int>(c.equippedArmor) << "\n";
    file << "SHIELD " << (c.hasShield ? 1 : 0) << "\n";
    file << "WEAPON " << c.weaponDamageSides << " " << c.weaponDamageBonus << " " << c.weaponName << "\n";
    // Carried (not-equipped) items -- see character/Equipment.h. Reuses the
    // ARMOR/SHIELD/WEAPON keywords above for each entry's own line (plus a
    // POTION keyword with no equipped-slot counterpart, since potions are
    // never equipped), but these are consumed by load() via a stateful
    // counter, same trick ZONESTACK uses below, so there's no collision
    // with the equipped-slot keywords above.
    file << "INVENTORY " << c.inventory.size() << "\n";
    for (const auto& item : c.inventory) {
        switch (item.kind) {
            case character::ItemKind::Armor:
                file << "ARMOR " << static_cast<int>(item.armorId) << "\n";
                break;
            case character::ItemKind::Shield:
                file << "SHIELD\n";
                break;
            case character::ItemKind::Weapon:
                file << "WEAPON " << item.weaponDamageSides << " " << item.weaponDamageBonus << " "
                     << item.weaponName << "\n";
                break;
            case character::ItemKind::Potion:
                file << "POTION\n";
                break;
        }
    }
    file << "SPELLSTODAY " << c.spellsCastToday << " " << c.spellsCastDay << "\n";
    file << "RESTDAY " << c.lastRestDay << "\n";
    file << "MODE " << (state.mode == Mode::Zone ? "ZONE" : "OVERWORLD") << "\n";
    file << "POS " << state.x << " " << state.y << "\n";
    file << "HOURS " << state.hoursElapsed << "\n";
    file << "VISITED " << state.visitedLocations.size();
    for (const auto& id : state.visitedLocations) {
        file << " " << id;
    }
    file << "\n";
    file << "MET " << state.metCharacters.size();
    for (const auto& id : state.metCharacters) {
        file << " " << id;
    }
    file << "\n";
    file << "BOAT " << (state.hasBoat ? 1 : 0) << "\n";
    // Quest progress and lifetime kill tallies -- one line per entry, no
    // count prefix (unlike VISITED/MET, these are id+int pairs, not bare
    // ids, so packing them onto one line would need its own delimiter).
    // Must stay here, before ZONE/ZONESTACK -- load()'s ZONESTACK handling
    // relies on it being written last with nothing after it (see below).
    for (const auto& [id, status] : state.quests) {
        file << "QUEST " << id << " " << static_cast<int>(status) << "\n";
    }
    for (const auto& [id, count] : state.monsterKills) {
        file << "KILL " << id << " " << count << "\n";
    }
    if (state.mode == Mode::Zone) {
        file << "ZONE " << state.currentZoneId << "\n";
        file << "ZONEPOS " << state.zoneX << " " << state.zoneY << "\n";
    }
    file << "ZONESTACK " << state.zoneStack.size() << "\n";
    for (const auto& entry : state.zoneStack) {
        file << entry.zoneId << " " << entry.x << " " << entry.y << "\n";
    }
}

GameState SaveGame::load(const std::string& path) {
    std::ifstream file(path);
    if (!file) {
        throw std::runtime_error("Could not open save file: " + path);
    }

    GameState state;
    bool haveMode = false;
    bool modeIsZone = false;
    bool haveZoneLine = false;
    bool haveZonePosLine = false;
    int zoneStackCount = -1;
    int inventoryCount = -1;

    std::string line;
    int lineNumber = 0;
    while (std::getline(file, line)) {
        ++lineNumber;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        std::string trimmed = trim(line);
        if (trimmed.empty() || trimmed[0] == '#') continue;

        // Once ZONESTACK's count has been read, its N entry lines are plain
        // "<zoneId> <x> <y>" rows, not KEYWORD lines -- consume them here
        // instead of falling into the keyword dispatch below. Relies on
        // save() always writing ZONESTACK last with nothing after it.
        if (zoneStackCount >= 0 && static_cast<int>(state.zoneStack.size()) < zoneStackCount) {
            std::istringstream iss(trimmed);
            ZoneReturnPoint entry;
            if (!(iss >> entry.zoneId >> entry.x >> entry.y)) {
                fail(path, lineNumber, "malformed ZONESTACK entry (expected: <zoneId> <x> <y>)");
            }
            state.zoneStack.push_back(std::move(entry));
            continue;
        }

        // Same trick as ZONESTACK above: once INVENTORY's count has been
        // read, its N entry lines are raw "ARMOR <id>" / "SHIELD" /
        // "WEAPON <sides> <bonus> <name...>" rows -- consumed here instead
        // of the general keyword dispatch below, so they don't collide with
        // the top-level ARMOR/SHIELD/WEAPON handlers (which set the
        // *equipped* slot, not inventory). Relies on save() always writing
        // INVENTORY's entries with nothing else interspersed.
        if (inventoryCount >= 0 && static_cast<int>(state.character.inventory.size()) < inventoryCount) {
            auto [itemKeyword, itemRest] = splitKeyword(trimmed);
            std::istringstream itemIss(itemRest);
            character::InventoryItem item;
            if (itemKeyword == "ARMOR") {
                item.kind = character::ItemKind::Armor;
                item.armorId = parseEnumInt<character::ArmorId>(path, lineNumber, itemRest, "inventory ARMOR", 4);
            } else if (itemKeyword == "SHIELD") {
                item.kind = character::ItemKind::Shield;
            } else if (itemKeyword == "POTION") {
                item.kind = character::ItemKind::Potion;
            } else if (itemKeyword == "WEAPON") {
                item.kind = character::ItemKind::Weapon;
                if (!(itemIss >> item.weaponDamageSides >> item.weaponDamageBonus)) {
                    fail(path, lineNumber, "malformed inventory WEAPON entry (expected: WEAPON sides bonus name...)");
                }
                std::string name;
                std::getline(itemIss, name);
                item.weaponName = trim(name);
            } else {
                fail(path, lineNumber, "unknown inventory item keyword '" + itemKeyword + "'");
            }
            state.character.inventory.push_back(std::move(item));
            continue;
        }

        auto [keyword, rest] = splitKeyword(trimmed);
        std::istringstream iss(rest);

        if (keyword == "NAME") {
            state.character.name = rest;
        } else if (keyword == "RACE") {
            state.character.race = parseEnumInt<character::RaceId>(
                path, lineNumber, rest, "RACE", static_cast<int>(character::kAllRaces.size()));
        } else if (keyword == "SUBRACE") {
            // None + every elf subrace + every dwarf subrace -- see character/Race.h.
            int subraceCount = 1 + static_cast<int>(character::kElfSubraces.size()) +
                                static_cast<int>(character::kDwarfSubraces.size());
            state.character.subrace =
                parseEnumInt<character::SubraceId>(path, lineNumber, rest, "SUBRACE", subraceCount);
        } else if (keyword == "CLASS") {
            // kClassIdCount, not kAllClasses.size() -- kAllClasses is only
            // the core four offered in the ordinary class menu, and
            // deliberately excludes Tinker (see character/CharClass.h), but
            // a saved Gnome character's CLASS int can legitimately be
            // Tinker's ordinal, which kAllClasses.size() would wrongly reject.
            state.character.charClass = parseEnumInt<character::ClassId>(
                path, lineNumber, rest, "CLASS", character::kClassIdCount);
        } else if (keyword == "ALIGNMENT") {
            state.character.alignment = parseEnumInt<character::Alignment>(path, lineNumber, rest, "ALIGNMENT", 9);
        } else if (keyword == "KNIGHTORDER") {
            // KnightOrder has 2 values (None, Crown) -- see character/Knighthood.h.
            state.character.knightOrder =
                parseEnumInt<character::KnightOrder>(path, lineNumber, rest, "KNIGHTORDER", 2);
        } else if (keyword == "ROBE") {
            // RobeColor has 4 values (None, White, Red, Black) -- see character/WizardOrder.h.
            state.character.robeColor = parseEnumInt<character::RobeColor>(path, lineNumber, rest, "ROBE", 4);
        } else if (keyword == "SCORES") {
            if (!(iss >> state.character.scores.strength >> state.character.scores.dexterity >>
                  state.character.scores.constitution >> state.character.scores.intelligence >>
                  state.character.scores.wisdom >> state.character.scores.charisma)) {
                fail(path, lineNumber, "malformed SCORES (expected 6 integers)");
            }
        } else if (keyword == "STRPCT") {
            if (!(iss >> state.character.exceptionalStrengthPercentile)) fail(path, lineNumber, "malformed STRPCT");
        } else if (keyword == "LEVEL") {
            if (!(iss >> state.character.level)) fail(path, lineNumber, "malformed LEVEL");
        } else if (keyword == "EXP") {
            if (!(iss >> state.character.experience)) fail(path, lineNumber, "malformed EXP");
        } else if (keyword == "HP") {
            if (!(iss >> state.character.currentHp >> state.character.maxHp)) {
                fail(path, lineNumber, "malformed HP (expected: HP current max)");
            }
        } else if (keyword == "AC") {
            if (!(iss >> state.character.armorClass)) fail(path, lineNumber, "malformed AC");
        } else if (keyword == "THAC0") {
            if (!(iss >> state.character.thac0)) fail(path, lineNumber, "malformed THAC0");
        } else if (keyword == "SAVES") {
            for (int i = 0; i < static_cast<int>(character::SaveCategory::Count); ++i) {
                int value;
                if (!(iss >> value)) fail(path, lineNumber, "malformed SAVES (expected 5 integers)");
                state.character.saves.at(static_cast<character::SaveCategory>(i)) = value;
            }
        } else if (keyword == "STEEL") {
            if (!(iss >> state.character.steelPieces)) fail(path, lineNumber, "malformed STEEL");
        } else if (keyword == "GOLD") {
            // Legacy pre-rename keyword (see docs/GOTCHAS.md) -- save()
            // never writes this anymore, but a save file written before the
            // Gold->Steel rename still has it. Accepted permanently so an
            // old save keeps loading; the next autosave rewrites it as STEEL.
            if (!(iss >> state.character.steelPieces)) fail(path, lineNumber, "malformed GOLD");
        } else if (keyword == "ARMOR") {
            // 4 ArmorId values: None, Leather, ChainMail, SplintMail -- see character/Equipment.h.
            state.character.equippedArmor =
                parseEnumInt<character::ArmorId>(path, lineNumber, rest, "ARMOR", 4);
        } else if (keyword == "SHIELD") {
            int value = -1;
            if (!(iss >> value) || (value != 0 && value != 1)) {
                fail(path, lineNumber, "malformed SHIELD (expected 0 or 1)");
            }
            state.character.hasShield = value == 1;
        } else if (keyword == "WEAPON") {
            if (!(iss >> state.character.weaponDamageSides >> state.character.weaponDamageBonus)) {
                fail(path, lineNumber, "malformed WEAPON (expected: WEAPON damageSides damageBonus name...)");
            }
            std::string weaponName;
            std::getline(iss, weaponName);
            state.character.weaponName = trim(weaponName);
        } else if (keyword == "INVENTORY") {
            if (!(iss >> inventoryCount) || inventoryCount < 0) {
                fail(path, lineNumber, "malformed INVENTORY (expected a non-negative count)");
            }
        } else if (keyword == "SPELLSTODAY") {
            if (!(iss >> state.character.spellsCastToday >> state.character.spellsCastDay)) {
                fail(path, lineNumber, "malformed SPELLSTODAY (expected: SPELLSTODAY count day)");
            }
        } else if (keyword == "RESTDAY") {
            // Optional -- a save written before Milestone 40 simply has no
            // RESTDAY line, and Character::lastRestDay's default (-1, "never
            // rested") is the correct value for it anyway.
            if (!(iss >> state.character.lastRestDay)) fail(path, lineNumber, "malformed RESTDAY");
        } else if (keyword == "MODE") {
            if (rest == "ZONE") {
                modeIsZone = true;
            } else if (rest == "OVERWORLD") {
                modeIsZone = false;
            } else {
                fail(path, lineNumber, "malformed MODE (expected OVERWORLD or ZONE)");
            }
            haveMode = true;
        } else if (keyword == "POS") {
            if (!(iss >> state.x >> state.y)) fail(path, lineNumber, "malformed POS (expected: POS x y)");
        } else if (keyword == "HOURS") {
            if (!(iss >> state.hoursElapsed)) fail(path, lineNumber, "malformed HOURS");
        } else if (keyword == "VISITED") {
            int count;
            if (!(iss >> count) || count < 0) fail(path, lineNumber, "malformed VISITED (expected a count)");
            for (int i = 0; i < count; ++i) {
                std::string id;
                if (!(iss >> id)) fail(path, lineNumber, "VISITED has fewer ids than its count");
                state.visitedLocations.insert(id);
            }
        } else if (keyword == "MET") {
            int count;
            if (!(iss >> count) || count < 0) fail(path, lineNumber, "malformed MET (expected a count)");
            for (int i = 0; i < count; ++i) {
                std::string id;
                if (!(iss >> id)) fail(path, lineNumber, "MET has fewer ids than its count");
                state.metCharacters.insert(id);
            }
        } else if (keyword == "BOAT") {
            int value = -1;
            if (!(iss >> value) || (value != 0 && value != 1)) {
                fail(path, lineNumber, "malformed BOAT (expected 0 or 1)");
            }
            state.hasBoat = value == 1;
        } else if (keyword == "QUEST") {
            // Optional -- a save written before Milestone 51 simply has no
            // QUEST lines, and an empty state.quests (no quest started) is
            // the correct value for it anyway. Status is a raw enum int,
            // same convention as RACE/CLASS/ALIGNMENT. 0/1/2 == Active/
            // Complete/ReadyToTurnIn (ReadyToTurnIn added after this
            // milestone shipped -- see GameState.h); accepted here from day
            // one since QuestStatus is append-only-safe.
            std::string id;
            int statusValue = -1;
            if (!(iss >> id >> statusValue) || statusValue < 0 || statusValue > 2) {
                fail(path, lineNumber, "malformed QUEST (expected: QUEST <id> <0, 1, or 2>)");
            }
            state.quests[id] = static_cast<QuestStatus>(statusValue);
        } else if (keyword == "KILL") {
            // Optional, same backward-compat reasoning as QUEST above.
            std::string id;
            int count = -1;
            if (!(iss >> id >> count) || count < 0) {
                fail(path, lineNumber, "malformed KILL (expected: KILL <monster-id> <count>)");
            }
            state.monsterKills[id] = count;
        } else if (keyword == "ZONE") {
            state.currentZoneId = rest;
            haveZoneLine = true;
        } else if (keyword == "ZONEPOS") {
            if (!(iss >> state.zoneX >> state.zoneY)) {
                fail(path, lineNumber, "malformed ZONEPOS (expected: ZONEPOS x y)");
            }
            haveZonePosLine = true;
        } else if (keyword == "ZONESTACK") {
            if (!(iss >> zoneStackCount) || zoneStackCount < 0) {
                fail(path, lineNumber, "malformed ZONESTACK (expected a non-negative count)");
            }
        } else {
            fail(path, lineNumber, "unknown keyword '" + keyword + "'");
        }
    }

    if (!haveMode) fail(path, lineNumber + 1, "missing MODE");
    state.mode = modeIsZone ? Mode::Zone : Mode::Overworld;
    if (modeIsZone && (!haveZoneLine || !haveZonePosLine)) {
        fail(path, lineNumber + 1, "MODE ZONE requires both ZONE and ZONEPOS");
    }
    if (zoneStackCount < 0 || static_cast<int>(state.zoneStack.size()) != zoneStackCount) {
        fail(path, lineNumber + 1, "ZONESTACK entry count did not match its declared count");
    }
    // INVENTORY itself is optional (old saves predating this field simply
    // have no carried items -- see character::Character::inventory), but if
    // present its declared count must be fully satisfied.
    if (inventoryCount >= 0 && static_cast<int>(state.character.inventory.size()) != inventoryCount) {
        fail(path, lineNumber + 1, "INVENTORY entry count did not match its declared count");
    }

    return state;
}

} // namespace game
